<?php

namespace App\Filament\Employ\Resources;

use App\Enums\ActivateAgencyEnum;
use App\Enums\ActivateStatusEnum;
use App\Enums\BalanceTypeEnum;
use App\Enums\BayTypeEnum;
use App\Enums\FarType;
use App\Enums\LevelUserEnum;
use App\Enums\OrderStatusEnum;
use App\Enums\OrderTypeEnum;
use App\Enums\TaskAgencyEnum;
use App\Filament\Employ\Resources\OrderResource\Pages;
use App\Filament\Employ\Resources\OrderResource\RelationManagers;
use App\Helper\HelperBalance;
use App\Models\Agency;
use App\Models\Balance;
use App\Models\Branch;
use App\Models\City;
use App\Models\Order;
use App\Models\User;
use Carbon\Carbon;
use Error;
use Filament\Forms;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\DB;
use LaraZeus\Popover\Tables\PopoverColumn;


class OrderResource extends Resource
{
    protected static ?string $model = Order::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $pluralModelLabel = 'الشحنات';

    protected static ?string $label = 'شحنة';
    protected static ?string $navigationLabel = 'الشحنات';



    public static function canEdit(Model $record): bool
    {
        return parent::canEdit($record) && $record->status===OrderStatusEnum::PENDING; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('الطلبات')->schema([
                    Forms\Components\Fieldset::make('معلومات المرسل')
                        ->schema([
                            Forms\Components\Grid::make()->schema([
                                Forms\Components\Select::make('type')->options([
                                    OrderTypeEnum::HOME->value => OrderTypeEnum::HOME->getLabel(),
                                ])->label('نوع الطلب')->searchable()
                                    ->default(OrderTypeEnum::BRANCH->getLabel()),

                                Forms\Components\Select::make('sender_id')->relationship('sender', 'name')->label('معرف المرسل')
                                    ->afterStateUpdated(function ($state, $set) {
                                        $user = User::find($state);
                                        if ($user) {
                                            $set('sender_phone', $user->phone);
                                            $set('sender_address', $user->address);
                                            $set('city_source_id', $user?->city_id);

                                        }
                                    })->live()->searchable()->preload(),
                            ]),
                            Forms\Components\Grid::make()->schema([
                                Forms\Components\TextInput::make('general_sender_name')->label('اسم المرسل'),


                                Forms\Components\Select::make('branch_source_id')->relationship('branchSource', 'name')->label('اسم الفرع المرسل')
                                    ->afterStateUpdated(function ($state, $set) {
                                        $branch = Branch::find($state);
                                        if ($branch) {
                                            $set('city_source_id', $branch->city_id);
                                        }
                                    })->live()->required()->searchable()->preload(),
                            ]),
                            Forms\Components\Grid::make()->schema([
                                Forms\Components\TextInput::make('sender_phone')->label('رقم هاتف المرسل'),
                                Forms\Components\TextInput::make('sender_address')->label('عنوان المرسل'),
                            ]),
                            Forms\Components\Grid::make()->schema([
                                Forms\Components\Select::make('city_source_id')->relationship('citySource', 'name')
                                    ->label('من بلدة')->searchable()->preload(),
                            ]),
                        ]),

                    Forms\Components\Fieldset::make('معلومات المستلم')->schema([
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\Select::make('receive_id')->relationship('receive', 'name')->label('معرف المستلم')->searchable()->preload()
                                ->afterStateUpdated(function ($state, $set) {
                                    $user = User::find($state);
                                    if ($user) {
                                        $set('receive_phone', $user->phone);
                                        $set('receive_address', $user->address);
                                        $set('city_target_id', $user?->city_id);


                                    }
                                })->live(),


                        ]),
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\TextInput::make('receive_phone')->label('هاتف المستلم'),
                            Forms\Components\TextInput::make('receive_address')->label('عنوان المستلم'),
                        ]),
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\TextInput::make('global_name')->label('اسم المستلم'),


                            Forms\Components\Select::make('city_target_id')->relationship('cityTarget', 'name')
                                ->label('الى بلدة')->searchable()->preload(),
                        ]),

                    ]),


                    Forms\Components\Fieldset::make('معلومات الطلب')->schema([
                        Forms\Components\Grid::make(3)->schema([

                            Forms\Components\Select::make('size_id')
                                ->relationship('size', 'name')
                                ->label
                                ('فئة الحجم'),


                            Forms\Components\Select::make('unit_id')->relationship('unit', 'name')->label('الوحدة'),

                            Forms\Components\Select::make('weight_id')
                                ->relationship('weight', 'name')
                                ->label
                                ('فئة الوزن')->searchable()->preload(),
                        ]),


                    ]),

                    Forms\Components\Fieldset::make('الأجور')->schema([
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\TextInput::make('price')->numeric()->label('التحصيل')->default(0),
                            Forms\Components\TextInput::make('far')->numeric()->label('أجور الشحن')->default(1),

                            Forms\Components\Radio::make('far_sender')
                                ->options([
                                    true => 'المرسل',
                                    false => 'المستلم'
                                ])->required()->default(false)->inline()
                                ->label('أجور الشحن')->default(1),
                        ]),
                    ])
                ]),
                Forms\Components\Section::make('محتويات الطلب')
                    ->schema([
                        Forms\Components\Repeater::make('packages')->relationship('packages')->schema([
                            SpatieMediaLibraryFileUpload::make('package')->label('صورة الشحنة')->collection('packages'),


                            Forms\Components\TextInput::make('info')->label('معلومات الشحنة'),

                            Forms\Components\TextInput::make('quantity')->numeric()->label('الكمية'),


                        ])
                            ->collapsible()
                            ->collapsed(),
                    ])->collapsible()->collapsed(true),


            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->poll(10)
            ->columns([
                PopoverColumn::make('qr_url')
                    ->trigger('click')
                    ->placement('right')
                    ->content(fn($record) => \LaraZeus\Qr\Facades\Qr::render($record->code))
                    ->icon('heroicon-o-qr-code'),

                Tables\Columns\TextColumn::make('id')->description(fn($record) => $record->code)->copyable(),


//                Tables\Columns\TextColumn::make('status')->label('حالة الطلب')


                Tables\Columns\TextColumn::make('type')->label('نوع الطلب')
                    ->description(fn($record) => $record->status?->getLabel())
                    ->searchable(),
                Tables\Columns\TextColumn::make('far_sender')->formatStateUsing(fn($state)=>FarType::tryFrom($state)?->getLabel())
                    ->color(fn($state)=>FarType::tryFrom($state)?->getColor())
                    ->icon(fn($state)=>FarType::tryFrom($state)?->getIcon())
                    ->label('حالة الدفع')
                    ->description(fn($record) => $record->created_at->diffForHumans())
                    ->searchable(),

                Tables\Columns\TextColumn::make('unit.name')->label('نوع الشحنة'),

                Tables\Columns\TextColumn::make('price')->label('التحصيل')->description(fn($record) => 'اجور الشحن : ' . $record->far),
                Tables\Columns\TextColumn::make('sender.name')->label('اسم المرسل')->description(fn($record) => $record->general_sender_name)->searchable(),

                Tables\Columns\TextColumn::make('citySource.name')->label('من بلدة')->description(fn($record) => "إلى {$record->cityTarget?->name}")->searchable(),
                Tables\Columns\TextColumn::make('receive.name')->label('معرف المستلم ')->description(fn($record) => $record->global_name)->searchable(),
                Tables\Columns\TextColumn::make('receive_address')->label('هاتف المستلم ')->description(fn($record) => $record->receive_phone)
                    ->url(fn($record) => url('https://wa.me/' . ltrim($record?->receive_phone, '+')))->openUrlInNewTab()
                    ->searchable(),


            ])->defaultSort('created_at', 'desc')
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('success_pick')
                    ->form(function ($record) {
                        if ($record->far_sender == true && $record->far) {
                            return [
                                Forms\Components\Placeholder::make('msg')->content("أنت على وشك تأكيد إلتقاط الطلب وإستلام أجور الشحن {$record->far}")->extraAttributes(['style' => 'color:red;font-weight:900;font-size:1rem;'])
                            ];
                        }
                        return [
                            Forms\Components\Placeholder::make('msg')->content("أنت على وشك تأكيد إلتقاط الطلب ")->extraAttributes(['style' => 'color:red;font-weight:900;font-size:1rem;'])
                        ];
                    })
                    ->action(function ($record, $data) {
                        DB::beginTransaction();
                        try {
                            HelperBalance::completePicker($record);
                            $record->update(['status' => OrderStatusEnum::PICK->value]);
                            DB::commit();
                            Notification::make('success')->title('نجاح العملية')->body('تم تأكيد إلتقاط الطلب')->success()->send();
                        } catch (\Exception | Error $e) {
                            Notification::make('error')->title('فشل العملية')->body($e->getLine())->danger()->send();
                        }
                    })
                    ->label('تأكيد إلتقاط الشحنة')->button()->color('info')
                    ->visible(fn($record) => $record->pick_id == auth()->id() && $record->status == OrderStatusEnum::AGREE),
                Tables\Actions\Action::make('success_given')
                    ->form(function ($record) {
                        $price = $record->price;
                        $far = $record->far;
                        $totalPrice = $price;
                        if ($record->far_sender == false && $record->far > 0) {
                            $totalPrice = $price + $far;
                        }
                        if ($totalPrice > 0) {
                            return [
                                Forms\Components\Placeholder::make('msg')->content("أنت على وشك تأكيد تسليم الطلب وإستلام أجور الشحن {$totalPrice}")->extraAttributes(['style' => 'color:red;font-weight:900;font-size:1rem;'])
                            ];
                        }
                        return [
                            Forms\Components\Placeholder::make('msg')->content("أنت على وشك تأكيد تسليم الطلب ")->extraAttributes(['style' => 'color:red;font-weight:900;font-size:1rem;'])
                        ];
                    })
                    ->action(function ($record, $data) {
                        DB::beginTransaction();
                        try {
                            HelperBalance::completeOrder($record);
                            $record->update(['status' => OrderStatusEnum::SUCCESS->value]);
                            DB::commit();
                            Notification::make('success')->title('نجاح العملية')->body('تم تأكيد تسليم الطلب')->success()->send();
                        } catch (\Exception | Error $e) {
                            Notification::make('error')->title('فشل العملية')->body($e->getLine())->danger()->send();
                        }
                    })->label('تأكيد تسليم الشحنة')->button()->color('info')
                    ->visible(fn($record) => $record->given_id == auth()->id() && ($record->status == OrderStatusEnum::TRANSFER || $record->status == OrderStatusEnum::PICK)),

                Tables\Actions\Action::make('cancel_order')
                    ->form([
                        Forms\Components\Radio::make('status')->options([
                            OrderStatusEnum::CANCELED->value => OrderStatusEnum::CANCELED->getLabel(),
                            OrderStatusEnum::RETURNED->value => OrderStatusEnum::RETURNED->getLabel(),
                        ])->label('الحالة')->required()->default(OrderStatusEnum::CANCELED->value),
                        Forms\Components\Textarea::make('canceled_info')->label('سبب الإلغاء / الإعادة')
                    ])
                    ->action(function ($record, $data) {
                        DB::beginTransaction();
                        try {
                            $record->update(['status' => $data['status'], 'msg_cancel' => $data['msg_cancel']]);
                            DB::commit();
                            Notification::make('success')->title('نجاح العملية')->body('تم تغيير حالة الطلب')->success()->send();
                        } catch (\Exception | Error $e) {
                            Notification::make('error')->title('فشل العملية')->body($e->getLine())->danger()->send();
                        }
                    })->label('الإلغاء / الإعادة')->button()->color('danger')
                    ->visible(fn($record) => $record->status === OrderStatusEnum::PENDING || $record->status === OrderStatusEnum::AGREE || $record->status === OrderStatusEnum::PICK || $record->status === OrderStatusEnum::TRANSFER)


            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }




    public static function getRelations(): array
    {
        return [
            RelationManagers\AgenciesRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListOrders::route('/'),
            'create' => Pages\CreateOrder::route('/create'),
            'edit' => Pages\EditOrder::route('/{record}/edit'),
        ];
    }
}
