<?php

namespace App\Filament\Admin\Resources\UserResource\Pages;

use App\Filament\Admin\Resources\UserResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;


class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        while(true){
            $code=\Str::random(8);

            $user=User::where('num_id',$code)->first();
            if(!$user){
                $data['num_id']=$code;
                break;
            }
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
