<?php

namespace App\Filament\Branch\Resources\OrderResource\Pages;

use App\Enums\BayTypeEnum;
use App\Enums\OrderStatusEnum;
use App\Filament\Branch\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['code'] = "AWB" . now()->format('YmdHis'); // الطابع الزمني بتنسيق قصير
        $data['branch_source_id'] = auth()->user()->branch_id;

        $data['shipping_date'] = now()->format('Y-h-d');
        $data['status'] = OrderStatusEnum::PENDING->value;
        $data['bay_type'] = BayTypeEnum::AFTER->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
