<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\AccountStatmentResource\Pages;
use App\Filament\Admin\Resources\AccountStatmentResource\RelationManagers;
use App\Models\AccountStatment;
use App\Models\Balance;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class AccountStatmentResource extends Resource
{
    protected static ?string $model = Balance::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $navigationGroup = 'التقارير';
    protected static ?string $navigationLabel = 'كشف حساب';

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }


    public static function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return false;// TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return false;// TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return false;// TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->poll(10)
            ->modifyQueryUsing(fn($query) => $query->where('pending',false)->where('is_complete',true)->latest())
            ->columns([
                Tables\Columns\TextColumn::make('credit'),
                Tables\Columns\TextColumn::make('debit'),
                Tables\Columns\TextColumn::make('total'),
                Tables\Columns\TextColumn::make('info'),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('user_id')->relationship('user', 'name')->searchable()->default(0)->label('المستخدم'),
                Tables\Filters\SelectFilter::make('currency_id')->options([
                    1 => 'دولار',
                    2 => 'تركي'
                ])->default(1)->label('العملة'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAccountStatments::route('/'),
            'create' => Pages\CreateAccountStatment::route('/create'),
            'edit' => Pages\EditAccountStatment::route('/{record}/edit'),
        ];
    }
}
