<?php

namespace App\Filament\Employ\Resources\OrderResource\Pages;

use App\Filament\Employ\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListOrders extends ListRecords
{
    protected static string $resource = OrderResource::class;


    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()?->where(function($query){
            $query->where('pick_id',auth()->id());
            $query->orWhere('given_id',auth()->id());
            $query->orWhereHas('agencies',fn($query)=>$query->where('agencies.user_id',auth()->id()));
        }); // TODO: Change the autogenerated stub
    }
}
