<?php

namespace App\Filament\Admin\Pages;

use App\Filament\Admin\Widgets\BalanceCustomerView;
use App\Filament\Admin\Widgets\BalanceCustomerTRWidget;
use App\Filament\Admin\Widgets\BalanceCustomerWidget;
use App\Filament\Admin\Widgets\PendingBalanceCustomerTRYWidget;
use App\Filament\Admin\Widgets\PendingBalanceCustomerWidget;
use App\Models\Balance;
use App\Models\User;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Pages\Page;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;

class CustomerReport extends Page
{

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.admin.pages.customer-report';
    protected ?string $heading='أرصدة الزبائن';
    protected static ?string $navigationLabel='أرصدة الزبائن';
    protected static ?string $navigationGroup='التقارير';

    protected function getHeaderWidgets(): array
    {
        return array_merge(parent::getHeaderWidgets(),[
            BalanceCustomerView::class,
            BalanceCustomerTRWidget::class,
            BalanceCustomerWidget::class,
            PendingBalanceCustomerTRYWidget::class,
            PendingBalanceCustomerWidget::class
        ]); // TODO: Change the autogenerated stub
    }

}
