<?php

namespace App\Filament\Admin\Pages;

use App\Filament\Admin\Widgets\BalanceUserTRWidget;
use App\Filament\Admin\Widgets\BalanceUserWidget;
use App\Filament\Admin\Widgets\PendingBalanceTRYWidget;
use App\Filament\Admin\Widgets\PendingBalanceWidget;
use App\Models\Balance;
use App\Models\User;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Pages\Page;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;

class CustomerReport extends Page
{

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.admin.pages.customer-report';
    protected ?string $heading='أرصدة الزبائن';
    protected static ?string $navigationLabel='أرصدة الزبائن';
    protected static ?string $navigationGroup='التقارير';

    protected function getHeaderWidgets(): array
    {
        return array_merge(parent::getHeaderWidgets(),[
            BalanceUserTRWidget::class,
            BalanceUserWidget::class,
            PendingBalanceTRYWidget::class,
            PendingBalanceWidget::class
        ]); // TODO: Change the autogenerated stub
    }

}
